#!/usr/bin/env node
// Generates CSS custom-property blocks and a manifest from HelixScreen's own
// theme files, so the website renders in the same palettes the app ships.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

export const PALETTE_KEYS = [
  'screen_bg', 'overlay_bg', 'card_bg', 'elevated_bg',
  'border', 'text', 'text_muted', 'text_subtle',
  'primary', 'secondary', 'tertiary', 'info',
  'success', 'warning', 'danger', 'focus',
];

const DEFAULT_RADIUS = 3;
const DEFAULT_BORDER_WIDTH = 1;

export function cssVarName(key) {
  return `--hx-${key.replace(/_/g, '-')}`;
}

export function themeBlocks(slug, theme) {
  const blocks = [];
  for (const mode of ['dark', 'light']) {
    const palette = theme[mode];
    if (!palette) continue;
    const decls = PALETTE_KEYS
      .map((key) => `  ${cssVarName(key)}: ${palette[key]};`)
      .join('\n');
    const radius = theme.border_radius_size ?? DEFAULT_RADIUS;
    const borderWidth = theme.border_width ?? DEFAULT_BORDER_WIDTH;
    blocks.push(
      // Starlight owns `data-theme` and only ever tests it against 'light', so the
      // mode lives there and the slug gets its own attribute. Never merge these.
      `[data-hx-theme="${slug}"][data-theme="${mode}"] {\n${decls}\n` +
      `  --hx-radius: ${radius}px;\n` +
      `  --hx-border-width: ${borderWidth}px;\n}`
    );
  }
  return blocks.join('\n\n');
}

export function buildAll(themesDir) {
  const files = readdirSync(themesDir).filter((f) => f.endsWith('.json')).sort();
  const cssParts = [];
  const manifest = [];
  for (const file of files) {
    const slug = basename(file, '.json');
    const theme = JSON.parse(readFileSync(join(themesDir, file), 'utf8'));
    const modes = ['dark', 'light'].filter((m) => theme[m]);
    if (modes.length === 0) {
      console.warn(`[gen-themes] ${file} has neither a "dark" nor "light" palette; skipping.`);
      continue;
    }
    cssParts.push(themeBlocks(slug, theme));
    manifest.push({ slug, name: theme.name ?? slug, modes });
  }
  const header =
    '/* GENERATED by scripts/gen-themes.mjs from the helixscreen repo. Do not edit. */\n\n';
  return { css: header + cssParts.join('\n\n') + '\n', manifest };
}

const isMain = process.argv[1] &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (isMain) {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const themesDir = join(root, '..', 'helixscreen', 'assets', 'config', 'themes', 'defaults');
  let built;
  try {
    built = buildAll(themesDir);
  } catch (err) {
    // Committed output means a checkout without the sibling repo still builds.
    console.warn(`[gen-themes] ${themesDir} unavailable (${err.code ?? err.message}); keeping committed output.`);
    process.exit(0);
  }
  writeFileSync(join(root, 'src', 'styles', 'themes.generated.css'), built.css);
  mkdirSync(join(root, 'src', 'data'), { recursive: true });
  writeFileSync(
    join(root, 'src', 'data', 'themes.generated.json'),
    JSON.stringify(built.manifest, null, 2) + '\n'
  );
  console.log(`[gen-themes] wrote ${built.manifest.length} themes`);
}
